//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MountainBikeTracker_WP8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MountainBikeTracker_WP8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquiring GPS Signal....
        /// </summary>
        public static string AcquiringGPS {
            get {
                return ResourceManager.GetString("AcquiringGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alt.
        /// </summary>
        public static string AltLabel {
            get {
                return ResourceManager.GetString("AltLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountian Bike Tracker.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average.
        /// </summary>
        public static string AverageLabel {
            get {
                return ResourceManager.GetString("AverageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average speed.
        /// </summary>
        public static string AverageSpeedLabel {
            get {
                return ResourceManager.GetString("AverageSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteAppBarButtonText {
            get {
                return ResourceManager.GetString("DeleteAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance.
        /// </summary>
        public static string DistanceLabel {
            get {
                return ResourceManager.GetString("DistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dist.
        /// </summary>
        public static string DistLabel {
            get {
                return ResourceManager.GetString("DistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duration.
        /// </summary>
        public static string DurationLabel {
            get {
                return ResourceManager.GetString("DurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app accesses your phone&apos;s location. Is that ok?.
        /// </summary>
        public static string LocationRequest {
            get {
                return ResourceManager.GetString("LocationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max speed.
        /// </summary>
        public static string MaxSpeedLabel {
            get {
                return ResourceManager.GetString("MaxSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string PauseAppBarButtonText {
            get {
                return ResourceManager.GetString("PauseAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveAppBarMenuItemText {
            get {
                return ResourceManager.GetString("SaveAppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed.
        /// </summary>
        public static string SpeedLabel {
            get {
                return ResourceManager.GetString("SpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        public static string SpeedUnitsLabel {
            get {
                return ResourceManager.GetString("SpeedUnitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        public static string StartAppBarButtonText {
            get {
                return ResourceManager.GetString("StartAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start new ride.
        /// </summary>
        public static string StartNewRideButtonText {
            get {
                return ResourceManager.GetString("StartNewRideButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string StopAppBarButtonText {
            get {
                return ResourceManager.GetString("StopAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string TimeLabel {
            get {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total ascend.
        /// </summary>
        public static string TotalAscend {
            get {
                return ResourceManager.GetString("TotalAscend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total descend.
        /// </summary>
        public static string TotalDescend {
            get {
                return ResourceManager.GetString("TotalDescend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view history.
        /// </summary>
        public static string ViewHistoryButtonText {
            get {
                return ResourceManager.GetString("ViewHistoryButtonText", resourceCulture);
            }
        }
    }
}
