//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MountainBikeTracker_WP8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MountainBikeTracker_WP8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquiring GPS Signal....
        /// </summary>
        public static string AcquiringGPS {
            get {
                return ResourceManager.GetString("AcquiringGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alt.
        /// </summary>
        public static string AltLabel {
            get {
                return ResourceManager.GetString("AltLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountian Bike Tracker.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average.
        /// </summary>
        public static string AverageLabel {
            get {
                return ResourceManager.GetString("AverageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average speed.
        /// </summary>
        public static string AverageSpeedLabel {
            get {
                return ResourceManager.GetString("AverageSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteAppBarButtonText {
            get {
                return ResourceManager.GetString("DeleteAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string DeleteCurrentHistoryLabel {
            get {
                return ResourceManager.GetString("DeleteCurrentHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the ride?.
        /// </summary>
        public static string DeleteCurrentRequest {
            get {
                return ResourceManager.GetString("DeleteCurrentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string DeleteHistoryRequest {
            get {
                return ResourceManager.GetString("DeleteHistoryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave without saving?.
        /// </summary>
        public static string DeleteRecordedRequest {
            get {
                return ResourceManager.GetString("DeleteRecordedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string DeleteRecordingLabel {
            get {
                return ResourceManager.GetString("DeleteRecordingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording! Are you sure you want to leave?.
        /// </summary>
        public static string DeleteRecordingRequest {
            get {
                return ResourceManager.GetString("DeleteRecordingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distance.
        /// </summary>
        public static string DistanceLabel {
            get {
                return ResourceManager.GetString("DistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dist.
        /// </summary>
        public static string DistLabel {
            get {
                return ResourceManager.GetString("DistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duration.
        /// </summary>
        public static string DurationLabel {
            get {
                return ResourceManager.GetString("DurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationConsent.
        /// </summary>
        public static string LocationConsentText {
            get {
                return ResourceManager.GetString("LocationConsentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app accesses your phone&apos;s location. Is that ok?.
        /// </summary>
        public static string LocationRequest {
            get {
                return ResourceManager.GetString("LocationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock.
        /// </summary>
        public static string LockAppBarButtonText {
            get {
                return ResourceManager.GetString("LockAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        public static string LoginNotSuccessfulLabel {
            get {
                return ResourceManager.GetString("LoginNotSuccessfulLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not login at this time.  Please try again later..
        /// </summary>
        public static string LoginNotSuccessfulMessage {
            get {
                return ResourceManager.GetString("LoginNotSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logging in....
        /// </summary>
        public static string LoginStatusMessage {
            get {
                return ResourceManager.GetString("LoginStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max speed.
        /// </summary>
        public static string MaxSpeedLabel {
            get {
                return ResourceManager.GetString("MaxSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string PauseAppBarButtonText {
            get {
                return ResourceManager.GetString("PauseAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveAppBarMenuItemText {
            get {
                return ResourceManager.GetString("SaveAppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save ride.  Try again later..
        /// </summary>
        public static string SaveRideFailure {
            get {
                return ResourceManager.GetString("SaveRideFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed.
        /// </summary>
        public static string SpeedLabel {
            get {
                return ResourceManager.GetString("SpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        public static string SpeedUnitsLabel {
            get {
                return ResourceManager.GetString("SpeedUnitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        public static string StartAppBarButtonText {
            get {
                return ResourceManager.GetString("StartAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting new ride.
        /// </summary>
        public static string StartingNewRideMessage {
            get {
                return ResourceManager.GetString("StartingNewRideMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Ride Failure.
        /// </summary>
        public static string StartingNewRideNotSuccessfullLabel {
            get {
                return ResourceManager.GetString("StartingNewRideNotSuccessfullLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start a new ride at this time.  Please try again later..
        /// </summary>
        public static string StartingNewRideNotSuccessfullMessage {
            get {
                return ResourceManager.GetString("StartingNewRideNotSuccessfullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start new ride.
        /// </summary>
        public static string StartNewRideButtonText {
            get {
                return ResourceManager.GetString("StartNewRideButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string StopAppBarButtonText {
            get {
                return ResourceManager.GetString("StopAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string TimeLabel {
            get {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS signal.
        /// </summary>
        public static string TimeOutLabel {
            get {
                return ResourceManager.GetString("TimeOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not able to acquire GPS signal at this time.
        /// </summary>
        public static string TimeOutMessage {
            get {
                return ResourceManager.GetString("TimeOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total ascend.
        /// </summary>
        public static string TotalAscendLabel {
            get {
                return ResourceManager.GetString("TotalAscendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total descend.
        /// </summary>
        public static string TotalDescendLabel {
            get {
                return ResourceManager.GetString("TotalDescendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlock.
        /// </summary>
        public static string UnlockAppBarButtonText {
            get {
                return ResourceManager.GetString("UnlockAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view history.
        /// </summary>
        public static string ViewHistoryButtonText {
            get {
                return ResourceManager.GetString("ViewHistoryButtonText", resourceCulture);
            }
        }
    }
}
